#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        update-desktop-database /usr/share/applications 2>/dev/null || true
        ;;
    
    failed-upgrade)
        ;;
    
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
